### ISSUE TITLE
README links broken

### ISSUE THREAD

**Issue by iwahbe** [ferrite-rs/ferrite#2]
All links under "Code Organization" and the link under "Running Demo" are broken. The last link under "Documentation" is also broken. All are 404s.

**Comment by soareschen** [comment]
Should be fixed now. Thanks for reporting!

**Comment by iwahbe** [comment]
The link for functional is still broken 😄

**Comment by soareschen** [comment]
I have forgotten to push my commit. Fixed.

**Comment by najamelan** [comment]
The link to the book is still 404...

**Comment by soareschen** [comment]
Right, the repository was moved and the link got broken. I have fixed it and the new link is here: http://ferrite-rs.github.io/ferrite-book/
